# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asagiri < Formula
  desc "Deterministic orchestration for AI coding workflows"
  homepage "https://github.com/LaProgrammerie/asagiri"
  version "0.1.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "9e0e305953d148b6114ac96cadb5300d0dc1249abd8c6f645ee588cba83e49d5"

      define_method(:install) do
        bin.install "asa" => "asagiri"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "ca704656bb0c2afb8ead7219105e3fc68309f698940d6aef07a5846771a41e20"

      define_method(:install) do
        bin.install "asa" => "asagiri"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "cb3048b47ddc0a91488ecdb7d1429da1b4196bee42aa68886439484c923c14db"
      define_method(:install) do
        bin.install "asa" => "asagiri"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "25e6bfb65ff044eeed8a3702984d76d7fb6a932b8c487e4c49e0f0aa25c3c44a"
      define_method(:install) do
        bin.install "asa" => "asagiri"
      end
    end
  end

  test do
    system "#{bin}/asagiri", "version"
  end
end
