# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asagiri < Formula
  desc "Deterministic orchestration for AI coding workflows"
  homepage "https://github.com/LaProgrammerie/asagiri"
  version "0.1.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "7935cae4ae2db7899fc1e88c9d6d09520dab5c11ee8660c5eba2f75ef2adc919"

      define_method(:install) do
        bin.install "asa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "3c35bfcf2d66bf94e30f40c1f9f4e4e83ee06e8ecdee5f1b43a9db68764686fb"

      define_method(:install) do
        bin.install "asa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "62a837d9ccddd496fbc59f931e4c58625ffc66fd2a02962a35ca127c4704b57f"
      define_method(:install) do
        bin.install "asa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LaProgrammerie/asagiri/releases/download/v0.1.0-alpha.1/asa_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "77bbf63a65671c25e0bca05d05aa45214b615b82be359103ff6e9e61014f44a1"
      define_method(:install) do
        bin.install "asa"
      end
    end
  end

  test do
    system "#{bin}/asa", "version"
  end
end
